// additional libraries:
//https://pagecdn.io/lib/mathjs/9.4.4/math.min.js
//p5.js v1.11.2
var winsize=400; //random default value
var startTime;
var draw_idx = 0; 
var pause_idx = 0;
var elapsed_tmp = 0;
var elapsedTime;
var font;
var canvas;

var n_potential = 15; //13 + 2 control points
var xs   = new Array(n_potential); //-1, 0,1,2,3,4,5,6,7,8,9,10,11,12 ,13
var potential = new Array(3); //[potential_aa, potential_ab,potential_bb]

var num_ab = new Array(2);
var n_particle = 0;

var pos;  //array(Nx2)
var vel;  //array(Nx2)
var acc;  //array(Nx2)

var initpos;  //array(Nx2)
var initvel;  //array(Nx2)
var initacc;  //array(Nx2)

var type; //array(N) 0(a) or 1(b)
const n_box = 10;

//for interaction
const frate = 60; //framerate
const frate_sim = 150; //framerate for simulation (changes simulation speed, higher value = slow simulation)
const max_interaction_box = 8; //maximum interaction length in box wise
var max_interaction_length = max_interaction_box/n_box;
var pot_box_length = max_interaction_length/(n_potential-3);
var hs_dist = 0.05; //hard sphere - used for interaction_cutoff value  

var gamma = 0.5; //langevin thermostat
var kbT   = 0; //langevin thermostat, set as different number in setup()
var f_mult = 5; //force multiplier

var hue_0 = 0;
var hue_1 = 0;
var hist_color;
var temp_text;
var hover_frame=0;

function setup() {  
  font = "Courier New";
  winsize=Math.min(window.innerWidth,window.innerHeight);
  canvas = createCanvas(winsize,winsize);
  canvas.parent('sketch-holder');
  frameRate(frate);
  colorMode(HSB,1.0);
  background(0.0,0.0,0.0);
  
  //set color
  hue_0 = hl.random();
  hue_1 = hue_0 + 0.15 + 0.7*hl.random();
  if (hue_1 >= 1) {
    hue_1 = hue_1 - 1;
  }

  //set temperature, 5% chance of zero temperature.
  //else than that, resistor marking-like temperature will be set.
  //I wanted to show every solid-like(0~0.1), liquid-like(0.1~1), gas-like(1-10) region
  //and looks like this distribution would be best.
  
  let kbT_0 =  ( 1 + Math.floor(hl.random() * (9)));
  let kbT_1 =  (     Math.floor(hl.random() * (10)));
  let kbT_2 =  (-2 + Math.floor(hl.random() * (3)));
  let kbT_zero = Math.floor(hl.random() * (100));
  if (kbT_zero <= 4 ) {
    kbT = 0;
  } else {
    kbT = (kbT_0 + 0.1*kbT_1)*Math.pow(10,kbT_2);
	kbT = kbT.toFixed(3);
  }
  
  //set histogram color according to tewmperature Range
  //hot: color(0.1,1.0,0.7) //orange
  //mild: color(0.0,0.0,0.7) //white
  //cool: color(0.5,0.8,0.7) //mint
  //zero: color(0.6,1.0,0.6)
  let temps = ['Cool','Mild','Hot']
  let colors = [color(0.5,0.8,0.7), color(0.0,0.0,0.7), color(0.1,1.0,0.7)];
  if (kbT_zero <= 4 ) {
    hist_color = color(0.75,1.0,0.7);
	temp_text = "Absolute Zero";
  } else {
	hist_color = colors[kbT_2+2];
	temp_text = temps[kbT_2+2];
  }

  //build potential function as spline
  for (var i = 0; i < 3 ; i++) {
    potential[i] = new Array(n_potential);
  }
  
  for (var j = 0; j < n_potential; j++) {
    xs[j] = j-1;
  }
  
  for (var i = 0; i < 3 ; i++) {
    //aggregation prevention	  
	potential[i][0] = 1.5;
	potential[i][1] = 1.0;
	
	//random potential
	for (var j = 2; j < n_potential; j++) {
      potential[i][j] = (-1 + 2*hl.random())* sigmoid(2*(7-xs[j]));	
	}

  }
  
  
  //build particles and its position and initial velocity
  //number of particles: 2 + max(0,N(8,4)) for each a and b 
  num_ab = rand_normal();
  num_ab[0] = Math.min(8, 6 + Math.max(-2, Math.floor(2*num_ab[0])));
  num_ab[1] = Math.min(8, 6 + Math.max(-2, Math.floor(2*num_ab[1])));
  n_particle = num_ab[0] + num_ab[1];
  
  // Trait setting
  let traits = {
    "Temperature (kbT)": kbT,
    "Temperature (text)": temp_text,
    "# of particle A": num_ab[0],
    "# of particle B": num_ab[1],
  };

  // Set these traits so Highlight can read them
  hl.token.setTraits(traits);

  // Also set a name and description for this token
  hl.token.setName(`Squiggle potential #${hl.tx.tokenId}`);
  hl.token.setDescription(
    `Token #${hl.tx.tokenId}. "Pairwise potential function and 2D-particle dynamics simulation for binary system." The token shows a randomly generated pairwise potential function for a given binary system and its particle dynamics simulation. The potential function was generated by p5.js's curve method. Fixed values of high potential for zero distance were used to prevent overlapping between particles, and sigmoid functions were used to ignore interactions that had longer than specific distance cutoffs and did not make artifacts. Distributions of pair distance for the interaction type are depicted as histograms and drawn below the potential function. Due to the limited number of particles, pseudocounting was used to count the number of pairs for each distance bin. [index.js function setup()] The simulation was performed by velocity verlet method with Langevin thermostat with gamma of 0.5 and KbT of ${kbT}. Particles were assumed to have the same mass and act as hard spheres. The line between a particle pair shows the pairwise potential of the pair, where red has high potential and green has low potential. For visibility, the line having near-zero potential was drawn with low brightness.`
  );
  
  //initialize particles.
  //pos;  //array(Nx2) - coordinate of particles (have vaue of 0~1, which multipled by winsize at visualization)
  //position initialization without collision:
  //  To initialize positions without iterative placement and clash checking, following method was used:
  //    1.divide simulation space into 10x10 boxes (10: n_box)
  //    2.assign each particle to center of the one box randomly (array shuffling was used for this step)
  //    3.add random 2D-vector to each particle, where adding the random vector still contain the particle into the box
  //  This has way less complexity of position configurations from possible configurations without clash, 
  //  but since it's not for a research, it would be fine ;)  
  
  //lattice; //array(N) 0~max_lattice-1 -for interaction cutoff
  //vel;  //array(Nx2) - velocity of particles, which stands velocity of particle, in length unit of winsize and time unit of second. 
  //acc;  //array(Nx2) - accelation of particles
  //type; //array(N) 0(a) or 1(b)
  
  //build aux
  let boxids = new Array(n_box * (n_box-1));
  for (var i = 0; i < n_box * (n_box-1); i++) {
      boxids[i] = i;
  }
  shuffleArray(boxids);
  
  //build & initialize array
  pos     = new Array(n_particle);
  vel     = new Array(n_particle);
  acc     = new Array(n_particle);
  
  initpos     = new Array(n_particle);
  initvel     = new Array(n_particle);
  initacc     = new Array(n_particle);
  
  type    = new Array(n_particle);
  
  for (var i = 0; i < n_particle; i++) {
    pos[i] = new Array(2);
    initpos[i] = new Array(2);
        
    //circle diameter: 0.5*winsize/n_box = 10
    //circle radius:   0.25*winsize/n_box = 5
    //available random value: (-1/2 box size + circle radius) ~ (1/2 box size - circle radius)
    //-0.25*400/n_box ~ 0.25*400/n_box
    
    box_x  = boxids[i] % n_box;
    box_y  = 1 + Math.floor(boxids[i]/n_box);
    pos[i][0] = (1.0/n_box)*(0.5+box_x) + (0.25*1.0/n_box)*(-1 + 2*hl.random());
    pos[i][1] = (1.0/n_box)*(0.5+box_y) + (0.25*1.0/n_box)*(-1 + 2*hl.random());
    initpos[i][0] = pos[i][0];
    initpos[i][1] = pos[i][1];
    
    
    vel[i] = new Array(2);
    initvel[i] = new Array(2);
    let tmpvel = rand_normal();
    for (var j = 0; j < 2; j++) {
      vel[i][j] = tmpvel[j]*(1.0/n_box);
      initvel[i][j] = tmpvel[j]*(1.0/n_box);
    }
    
    acc[i] = new Array(2);
    initacc[i] = new Array(2);
    for (var j = 0; j < 2; j++) {
      acc[i][j] = 0;
      initacc[i][j] = 0;
    }
    
    if (i< num_ab[0]) {
      type[i] = 0;
    } else {
      type[i] = 1;
    }

  }
    
}
function draw() {
  winsize=Math.min(window.innerWidth,window.innerHeight);

  
  if (pause_idx == 0) {
  } else {
  }

  var pairs_draw;
  pairs_draw = get_interaction_pairs(n_particle, pos, max_interaction_length+hs_dist,0); //[[i,j,d],...]
  
  if(draw_idx == 1) {
    //draw simulation
    colorMode(HSB,1.0);
    background(0.0,0.0,0.0);
    strokeWeight(winsize/400);
	
    

	for (var idx = 0; idx < pairs_draw.length; idx++) {
	  let i = pairs_draw[idx][0];
      let j = pairs_draw[idx][1];
      let d = pairs_draw[idx][2];	  

      let pot_type = type[i] + type[j]; //0,0 -> 0(pot_aa), 0,1 / 1,0 ->1(pot_ab), 1,1 ->2(pot_bb)
      let pot = get_potential((d-hs_dist)/pot_box_length, potential[pot_type]);
      let pot_clip = Math.max(-1, Math.min(1, pot));
      let pot_hue = 0.167 *(1-pot_clip);
      stroke(pot_hue,1.0,Math.abs(pot_clip),Math.abs(pot_clip));
      if (Math.abs(pot_clip) > 0.15) {
        line(winsize * pos[i][0],winsize * pos[i][1],winsize * pos[j][0],winsize * pos[j][1]);
      }
	}

    for (var i =0; i<n_particle; i++) {
      if (type[i] === 0) {
        fill(hue_0,0.8,1.0);
        strokeWeight(0);
      } else {
        fill(hue_1,0.8,1.0);
        strokeWeight(0);
      }
      circle(winsize * pos[i][0],winsize * pos[i][1],hs_dist*winsize);
    }
    //button and text
    strokeWeight(0);
    textFont(font);
    textSize(winsize*0.05);
    textAlign(LEFT, CENTER);
    fill(0.0,0.0,0.4+0.025*hover_frame);
    text('Potential', winsize*0.01, winsize*0.04);
    fill(0.0,0.0,1.0);
    text('Simulation', winsize*0.36, winsize*0.04);
    
    if (overRect(winsize*0.01, winsize*0.02, textWidth('Potential'), winsize*0.06)) {
      hover_frame = Math.min(24, hover_frame + 1);
    } else {
      hover_frame = 0;
    }
  }
  else {
    let color1,color2,color3,color4,color5;
    let gradient = new Array(3);
    let hist = new Array(3); //3 x {2*(n_potential-5)} array
	let hist_temp = new Array(3);
	let hist_n = new Array(3);
	let hist_sum_temp = 0;
	colorMode(HSB,1.0);
    background(0.0,0.0,0.0);
    
    //color for potentials

    color1 = color(0.122, 0.96, 1.00); 
    color2 = color(0.053, 0.97, 0.98); 
    color3 = color(0.928, 1.00, 1.00); 
    color4 = color(0.736, 0.76, 0.93); 
    color5 = color(0.603, 0.77, 1.00); 

	
	for (var i = 0; i < 3; i++) {
      gradient[i] = drawingContext.createLinearGradient(0, 0.075*winsize*(1.5 + 4*i), 0, 0.075*winsize*(3.5 + 4*i) );// give gradient between potential_aa: -1 ~ 1
      gradient[i].addColorStop(0.1, color1);
      gradient[i].addColorStop(0.3, color2);
      gradient[i].addColorStop(0.5, color3);
      gradient[i].addColorStop(0.7, color4);
      gradient[i].addColorStop(0.9, color5);
  
    }
	//initialize histogram variables
	for (var i = 0; i < 3; i++) {
	  hist[i] = new Array(2*(n_potential-5));	  
	  for (var j = 0; j < 2*(n_potential-5); j++) {
		hist[i][j] = 0;
	  }
	
	  hist_temp[i] = 0;
	  hist_n[i] = 0;
	}

	for (var idx = 0; idx < pairs_draw.length; idx++) {
	  let i = pairs_draw[idx][0];
      let j = pairs_draw[idx][1];
      let d = pairs_draw[idx][2];	  

      let hist_i = Math.floor(2*(d-hs_dist)/pot_box_length);
      let remain = (2*(d-hs_dist)/pot_box_length) - hist_i;
		  
	  for (var tmp_i = 0; tmp_i < 3; tmp_i++) {
        hist_temp[tmp_i] = Math.exp(-2*(remain+0.5-tmp_i)*(remain+0.5-tmp_i));      
      }

      hist_sum_temp = Math.max(0.01, (hist_temp[0] + hist_temp[1] +  hist_temp[2]));  			   

      if (hist_i < 2*(n_potential-5)) {
	    let pot_type = type[i] + type[j]; //0,0 -> 0(pot_aa), 0,1 / 1,0 ->1(pot_ab), 1,1 ->2(pot_bb)  
	    //pseudocounting
        if (hist_i>0) {
		  hist[pot_type][hist_i-1] = hist[pot_type][hist_i-1]+hist_temp[0]/hist_sum_temp;
	    }
        if (hist_i< 2*n_potential-11) {
		  hist[pot_type][hist_i+1] = hist[pot_type][hist_i+1]+hist_temp[2]/hist_sum_temp;
		}
        hist[pot_type][hist_i] = hist[pot_type][hist_i]+hist_temp[1]/hist_sum_temp; 
      }
	}

    for (var i = 0; i < 3; i++) {
      for (var j = 0; j < 2*(n_potential-5); j++) {
        hist_n[i] = hist_n[i] + hist[i][j];   
      }
	}
	
    for (var i = 0; i < 3; i++) {
      hist_n[i] = Math.max(0.01,hist_n[i]);
	}		
	//draw histogram
	fill(hist_color);
    strokeWeight(0);
    for (var i = 0; i < 3; i++) {
      for (var j = 0; j < 2*(n_potential-5); j++) {
        rect(0.075*winsize*(0.5*j+2.125), 0.075*winsize*(4*i+4.5 - 1.6*hist[i][j]/hist_n[i]), 0.075*0.25*winsize, 0.075*winsize*(1.6*hist[i][j]/hist_n[i]) );
      }
	}
	
    //draw potential
	noFill();
    strokeWeight(4*winsize/400);
    for (var i = 0; i < 3; i++) {
      drawingContext.strokeStyle=gradient[i];
      for (var j = 0; j < n_potential-5; j++) {
        curve(0.075*winsize*(2+xs[j]), 0.075*winsize*(4*i+2.5 -potential[i][j]), 0.075*winsize*(2+xs[j+1]), 0.075*winsize*(4*i+2.5 -potential[i][j+1]), 0.075*winsize*(2+xs[j+2]), 0.075*winsize*(4*i+2.5 -potential[i][j+2]), 0.075*winsize*(2+xs[j+3]), 0.075*winsize*(4*i+2.5 -potential[i][j+3]));
      }
	}
    
    drawingContext.strokeStyle= color(0.0,0.0,1.0);
    strokeWeight(2*winsize/400);
    line(0.075*winsize*0.5, 0.075*winsize*2.5, 0.075*winsize*1.5, 0.075*winsize*2.5);
    line(0.075*winsize*0.5, 0.075*winsize*6.5, 0.075*winsize*1.5, 0.075*winsize*6.5);
    line(0.075*winsize*0.5, 0.075*winsize*10.5, 0.075*winsize*1.5, 0.075*winsize*10.5);

    fill(hue_0,0.8,1.0);
    strokeWeight(0);
    circle(0.075*winsize*0.5, 0.075*winsize*2.5, hs_dist*winsize);
    circle(0.075*winsize*1.5, 0.075*winsize*2.5, hs_dist*winsize);
    circle(0.075*winsize*0.5, 0.075*winsize*6.5, hs_dist*winsize);
    
    fill(hue_1,0.8,1.0);
    circle(0.075*winsize*1.5, 0.075*winsize*6.5,  hs_dist*winsize);
    circle(0.075*winsize*0.5, 0.075*winsize*10.5, hs_dist*winsize);
    circle(0.075*winsize*1.5, 0.075*winsize*10.5, hs_dist*winsize);

    //button and text
    strokeWeight(0);
    textFont(font);
    textSize(winsize*0.05);
    textAlign(LEFT, CENTER);
    fill(0.0,0.0,1.0);
    text('Potential', winsize*0.01, winsize*0.04);
    fill(0.0,0.0,0.4+0.025*hover_frame);
    text('Simulation', winsize*0.36, winsize*0.04); 
    
    if (overRect(winsize*0.36, winsize*0.02, textWidth('Simulation'), winsize*0.06)) {
      hover_frame = Math.min(24, hover_frame + 1);
    } else {
      hover_frame = 0;
    }
  }

    
  //do velocity verlet if not paused
  //https://en.wikipedia.org/wiki/Verlet_integration#Velocity_Verlet
  if (pause_idx === 0) {
    //1. calculate v(t+0.5dt) = v(t) + 0.5*a(t)dt
    
    //add langevin thermostat here. kbT came from total energy from initial state
    //https://en.wikipedia.org/wiki/Maxwell%E2%80%93Boltzmann_distribution
    //https://www.vasp.at/wiki/index.php/Langevin_thermostat
    //p_i' = F_i - gamma_i*p_i + friction_i (p_i' = ma)      
    //sigma_i = sqrt(2*mi*gamma_i*kbT/dt)
    
    for (var i = 0; i < n_particle; i++) {
      friction = rand_normal(); //N(0,1)
      friction[0] = friction[0] * Math.sqrt(2*1*gamma*kbT/(0.5/frate_sim));    
      friction[1] = friction[1] * Math.sqrt(2*1*gamma*kbT/(0.5/frate_sim));        
      for (var k = 0; k < 2; k++) {
        vel[i][k] = (1.0 - 0.5*gamma/frate_sim)*vel[i][k] + (0.5/frate_sim)*acc[i][k] + (0.5/frate_sim)*friction[k];
      }
    }    
    
    //2. calculate x(t+dt) = x(t) +v(t+0.5dt)dt
    for (var i = 0; i < n_particle; i++) {
      for (var k = 0; k < 2; k++) {
        pos[i][k] = pos[i][k] + vel[i][k]*(1.0/frate_sim);
      }
      //for (var j = 0; j < 2; j++) {
      //  box[i][j] = Math.floor(pos[i][j]*n_box);
      //}
    }
    //3. calculate a(t+dt) from the potential using x(t+dt)
    //interaction with other particle part
    //d<0.05: hard sphere collision
    //d>0.05: interact with potential, using (d-0.05)
    
    //3.1: reset a(t)
    let pairs = get_interaction_pairs(n_particle, pos, max_interaction_length+hs_dist,hs_dist); //[[i,j,d],...]
    for (var i = 0; i < n_particle; i++) {
      for (var k = 0; k < 2; k++) {
        acc[i][k] = 0;
      }
    }
	
	for (var idx = 0; idx < pairs.length; idx++) {
	  let i = pairs[idx][0];
      let j = pairs[idx][1];
      let d = pairs[idx][2];	  

      let force = 0;
	  let pot_type = type[i] + type[j]; //0,0 -> 0(pot_aa), 0,1 / 1,0 ->1(pot_ab), 1,1 ->2(pot_bb)
      let eps = 0.0000001;
      let acc_vec  = [(pos[i][0] - pos[j][0])/(d+eps) , (pos[i][1] - pos[j][1])/(d+eps) ]; //           
	  force = get_force((d-hs_dist)/pot_box_length, potential[pot_type]);
		  
      //let mass = 1
      acc[i][0] += f_mult*(force)*acc_vec[0]; 
      acc[i][1] += f_mult*(force)*acc_vec[1]; 
      acc[j][0] -= f_mult*(force)*acc_vec[0]; 
      acc[j][1] -= f_mult*(force)*acc_vec[1];
    }
    
    //4. calculate v(t+dt) = v(t+0.5dt) +0.5*a(a+dt)*dt
    //add langevin thermostat here. kbT came from total energy from initial state        
    for (var i = 0; i < n_particle; i++) {
      friction = rand_normal(); //N(0,1)
      friction[0] = friction[0] * Math.sqrt(2*1*gamma*kbT/(0.5/frate_sim));    
      friction[1] = friction[1] * Math.sqrt(2*1*gamma*kbT/(0.5/frate_sim));    
      for (var k = 0; k < 2; k++) {
        vel[i][k] = (1.0 - 0.5*gamma/frate_sim)*vel[i][k] + (0.5/frate_sim)*acc[i][k] + (0.5/frate_sim)*friction[k];
      }
    }
    //5. collision
    //collision with wall
    for (var i = 0; i < n_particle; i++) {
      if (pos[i][0] < 0.5*hs_dist ) {
        pos[i][0] = 0.002 + 0.5*hs_dist;
        vel[i][0] = -1*vel[i][0];
      }
      if (pos[i][0] > (1-0.5*hs_dist) ) {
        pos[i][0] = (0.998-0.5*hs_dist);
        vel[i][0] = -1*vel[i][0];
      }
	  //y: 0~(1/n_box)*winsize: place for buttom
      if (pos[i][1] < (0.5*hs_dist+ 1.0/n_box) ) {
        pos[i][1] = (0.002+ 0.5*hs_dist + 1.0/n_box);
        vel[i][1] = -1*vel[i][1];
      }
      if (pos[i][1] > (1-0.5*hs_dist) ) {
        pos[i][1] = (0.998-0.5*hs_dist);
        vel[i][1] = -1*vel[i][1];
      }
    }
    //collision with particle
	let pairs_hs = get_interaction_pairs(n_particle, pos, hs_dist,0)
	for (var idx = 0; idx < pairs_hs.length; idx++) {
	  let i = pairs_hs[idx][0];
      let j = pairs_hs[idx][1];
      let d = pairs_hs[idx][2];
	  
      let eps = 0.0000001;
      let acc_vec  = [(pos[i][0] - pos[j][0])/Math.max(eps,d) , (pos[i][1] - pos[j][1])/Math.max(eps,d) ];
          
	  //hard sphere collision 
      //https://scipython.com/blog/two-dimensional-collisions/
      //v1 -= dot((v1-v2)*(r1-r2) * (r1-r2)/d_sq 
      //v2 += dot((v1-v2)*(r1-r2) * (r1-r2)/d_sq
      let vel_diff = [ vel[i][0] - vel[j][0],  vel[i][1] - vel[j][1] ];
      vel[i][0] -= 0.9*(vel_diff[0]*acc_vec[0] + vel_diff[1]*acc_vec[1])*acc_vec[0];
      vel[i][1] -= 0.9*(vel_diff[0]*acc_vec[0] + vel_diff[1]*acc_vec[1])*acc_vec[1];
      vel[j][0] += 0.9*(vel_diff[0]*acc_vec[0] + vel_diff[1]*acc_vec[1])*acc_vec[0];
      vel[j][1] += 0.9*(vel_diff[0]*acc_vec[0] + vel_diff[1]*acc_vec[1])*acc_vec[1];
      //position treat 
      let pos_diff = [ pos[i][0] - pos[j][0],  pos[i][1] - pos[j][1] ];
      pos[i][0] += 0.5*pos_diff[0]*(hs_dist-d)/Math.max(eps,d);
      pos[i][1] += 0.5*pos_diff[1]*(hs_dist-d)/Math.max(eps,d);
      pos[j][0] -= 0.5*pos_diff[0]*(hs_dist-d)/Math.max(eps,d);
      pos[j][1] -= 0.5*pos_diff[1]*(hs_dist-d)/Math.max(eps,d);	  
    }
    
  }
}


function windowResized() {
  winsize=Math.min(window.innerWidth,window.innerHeight);
  resizeCanvas(winsize, winsize);
}

function keyPressed() {
  if (keyCode == 83) {
    if (draw_idx === 1) {
      save("simulation.jpg");
    }
    else {
      save("potential.jpg");}
  }
  else if (keyCode == 82) {
    //reset
    for (var i = 0; i < n_particle; i++) {
      for (var j = 0; j < 2; j++) {
        pos[i][j] = initpos[i][j];
        vel[i][j] = initvel[i][j];
        acc[i][j] = initacc[i][j];
      }
    }
    //elapsed_tmp = 0;
    //startTime = millis();
  }  
  else if (keyCode == 32)  {
    if (pause_idx === 0) {
      pause_idx = 1;
    } else {
      pause_idx = 0;
    }
  }
}

function mouseClicked() {
	
	
  if (mouseX > winsize*0.36 && mouseX < (winsize*0.36+textWidth('Simulation')) && mouseY > winsize*0.02 && mouseY < winsize*0.08) {
    draw_idx = 1;
  }
  if (mouseX > winsize*0.01 && mouseX < (winsize*0.01+textWidth('Potential')) && mouseY > winsize*0.02 && mouseY < winsize*0.08) {
    draw_idx = 0;
  }
}
function sigmoid(x) {
  return Math.exp(x) / (Math.exp(x) + 1)
}

function rand_normal()  {
  //Box-Muller Transform:
  //from https://en.wikipedia.org/wiki/Box%E2%80%93Muller_transform
  //return [ N(0,1), N(0,1) ] 

  let u    =   1 - hl.random(); // Converting [0,1) to (0,1]
  let phi  =   2 * Math.PI * hl.random();
  let R    =   Math.sqrt(  -2 * Math.log( u )  );
  let x    =   R * Math.cos(phi);
  let y    =   R * Math.sin(phi);

  // Return values:
  return [x,y];
}

function shuffleArray(array) {
  //Fisher–Yates_shuffle
  //from https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle
  for (let i = array.length - 1; i >= 0; i--) {
    const j = Math.floor(hl.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
}

function get_force(r, pot_s) {
  //calculate force as -d(Potential)/dx at x = r
  //which will be -ty/tx, but tx is fixed at 1, if xs is given as -1,0,1,2,3,4,.... 
  //  and tx doesn't need to be calculated in this project.
  //xs: xs used in potential spline function - not used now. but should have a value of -1,0,1,2,3,4,....
  //pot_s: either potential_aa, potential_ab, potential_bb   

  let i =  Math.min(pot_s.length, Math.max(0,Math.floor(r))); //for numerical stability
  let j = (r-i);
  //let tx = curveTangent(xs[i], xs[i+1], xs[i+2], xs[i+3], j);
  let ty = curveTangent(pot_s[i], pot_s[i+1], pot_s[i+2], pot_s[i+3], j);
  return -1*ty;
}

function get_potential(r, pot_s) {
  //calculate potential at r
  //pot_s: either potential_aa, potential_ab, potential_bb   
  let i = Math.min(pot_s.length, Math.max(0,Math.floor(r))); //for numerical stability
  let j = (r-i);
  let y = curvePoint(pot_s[i], pot_s[i+1], pot_s[i+2], pot_s[i+3], j);
  return y;
}

function get_interaction_pairs(n_particle, pos, max_interaction_length, min_interaction_length) {
  //return interaction pair, with format of [ [i, j, d],... ]
  //i,j: index of particle with interacting pair | d: distance between particle i and j  
  let result_tmp = Array( n_particle * (n_particle-1) / 2 );
  let result;
  let n_pairs = 0;
  for (var i = 0; i < n_particle; i++) {
    for (var j = 0; j < i; j++) {
      //lessen sqrt calls
      if (Math.abs(pos[i][0] - pos[j][0]) > (max_interaction_length)) {
        continue;
      }
      if (Math.abs(pos[i][1] - pos[j][1]) > (max_interaction_length)) {
        continue;
      }

      let d = Math.sqrt((pos[i][0] - pos[j][0])*(pos[i][0] - pos[j][0]) + (pos[i][1] - pos[j][1])*(pos[i][1] - pos[j][1]));
      if (d > max_interaction_length) {
        continue;
      }
      if (d < min_interaction_length){
        continue
      }
      else {
        result_tmp[n_pairs] = [i,j,d];
		n_pairs = n_pairs + 1;
      }        
    }
  }
  result = result_tmp.slice(0,n_pairs);
  return result;
}
  
function overRect(x, y, w, h) {
	if (mouseX > x && mouseX < x+w && mouseY > y && mouseY < y+h) {
	  return true;	
	} else {
	  return false;	
	}
}